[tool.poetry]
name = "hyperdome"
version = "0.2.0"
description = "The safest place to reach out"
authors = ["Skyelar Craver <scravers@protonmail.com>", "Steven Pitts <makusu2@gmail.com>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "~3.8"
cryptography = "2.9"
itsdangerous = "1.1.0"
stem = "1.8.0"
Flask = "1.1.2"
Jinja2 = "2.11.1"
PyQt5 = "5.14.2"
requests = "2.23.0"
pefile = "^2019.4.18"

[tool.poetry.dev-dependencies]
pyinstaller = "3.6"
setuptools = "46.1.3"
pytest = "5.4.1"
pytest-qt = "3.3.0"
bandit = "1.6.2"
black = "19.10b0"
pywin32-ctypes = {version = "^0.2.0", platform = "windows"}

[build-system]
requires = ["poetry==0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
hyperdome_client = "hyperdome.client.scripts.start_client:start"
hyperdome_server = "hyperdome.server.scripts.cli:admin"
